local servers = { 'nil_ls' } -- use exrc/.nvim.lua to set up project-specific lsps

vim.lsp.enable('lua_ls')
-- local capabilities = vim.lsp.protocol.make_client_capabilities()
-- capabilities = require('cmp_nvim_lsp').default_capabilities(capabilities)
--
-- local lsp_common = require('vorber.lsp_common')
--
-- local setup = function(server)
--     server.setup {
--         autostart = true,
--         on_attach = lsp_common.lsp_on_attach,
--         flags = {
--             debounce_text_changes = 150,
--         },
--        capabilities = lsp_common.lsp_client_capabilities(),
--     }
-- end
--
-- for _, lsp in ipairs(servers) do
--     setup(require('lspconfig')[lsp])
-- end
--
-- -- setup stuff for lua, since all configs are in it anyway
-- local runtime_path = vim.split(package.path, ';')
-- table.insert(runtime_path, 'lua/?.lua')
-- table.insert(runtime_path, 'lua/?/init.lua')
--
-- require('lspconfig').lua_ls.setup {
--     on_attach = lsp_common.lsp_on_attach,
--     capabilities = lsp_common.lsp_client_capabilities(),
--     settings = {
--         Lua = {
--             runtime = {
--                 version = 'LuaJIT',
--                 path = runtime_path,
--             },
--             diagnostics = {
--                 globals = { 'vim', 'require' },
--             },
--             workspace = {
--                 library = vim.api.nvim_get_runtime_file('', true),
--                 checkThirdParty = false,
--             },
--             telemetry = { enable = false },
--         },
--     },
-- }
